const crypto = require('crypto');
const db = require('../db');
const { fetchWithTimeout } = require('../utils/fetchWithTimeout');
const { encrypt, decrypt } = require('../utils/encryption');

// Secret used to sign (HMAC) the `state` parameter in the OAuth flow. REQUIRED, with no
// fallback to any other variable.
//
// Two earlier versions of this line were wrong in the same way. The first fell back to a fixed
// 'default_secret' literal visible in the source; the second fell back to APP_PASSWORD. The
// second looked safe - APP_PASSWORD is required for the backend to start anyway - but it made a
// single value both the OAuth signing key and the key material for encrypting the database
// (utils/encryption.js), and backend/.env.example shipped a CONCRETE value for it, committed to
// the repository. Anyone who read the repo could therefore sign
// `<victimId>:google_link:<salt>:<hmac>`, complete the Google consent screen on their OWN Google
// account, and routes/auth.js would write that Google account onto the victim's user row - after
// which the ordinary "Sign in with Google" button issues a session for the victim's account.
//
// Hence fail-fast instead of a quiet downgrade: a deployment that silently signs state with a
// weaker (or publicly known) secret looks perfectly healthy while its CSRF protection is
// forgeable, and nothing in the logs would ever say so. Refusing to start is the louder, safer
// failure.
const OAUTH_STATE_SECRET = process.env.OAUTH_STATE_SECRET;
if (!OAUTH_STATE_SECRET) {
  throw new Error(
    'OAUTH_STATE_SECRET is missing from the environment. It signs the `state` parameter of the ' +
    'OAuth flow (Oura/Withings/Google) and must be a dedicated random value - NOT APP_PASSWORD ' +
    'and not any other secret reused elsewhere. Generate one with `openssl rand -hex 32` and add ' +
    'OAUTH_STATE_SECRET=<value> to backend/.env (see backend/docs/secret-rotation.md).'
  );
}

// Helper for reading configuration from the app_config table. decrypt() is safe to call for
// EVERY key, not only the secret ones in APP_SECRET_CONFIG_KEYS - for values never encrypted
// by encrypt() (see utils/encryption.js) it is
// no-opem, bo brakuje im rozpoznawalnego prefiksu.
async function getAppConfig(key) {
  if (key === 'app_url' && process.env.APP_URL) {
    return process.env.APP_URL;
  }
  const row = await db.get(`SELECT value FROM app_config WHERE key = ?`, [key]);
  return row ? decrypt(row.value) : null;
}

// Helper for reading a specific user's settings - decrypt() as above, safe for non-secret
// values (a no-op without the enc:v1: prefix).
async function getUserSetting(userId, key) {
  const row = await db.get(`SELECT value FROM settings WHERE user_id = ? AND key = ?`, [userId, key]);
  return row ? decrypt(row.value) : null;
}

// How long a signed `state` stays acceptable. The state used to carry no timestamp at all,
// which made every signature eternal: GET /api/auth/google is a PUBLIC route (see the
// exception list in middleware/auth.js), so anyone could request it, read the state out of
// the 302 Location header, and keep that one string as a working login-CSRF ingredient for
// months - nothing in the flow ever aged it out or recorded that it had been used.
//
// Ten minutes is the window Google itself gives an authorization code, so a legitimate user
// who reaches the consent screen and approves it is always inside it; a state harvested and
// then delivered to a victim by e-mail, chat or a shortened link almost never is.
const OAUTH_STATE_MAX_AGE_MS = 10 * 60 * 1000;
// Tolerance for a state minted a moment "in the future" relative to the verifying process.
// Both ends are the same container today, but the value is signed on one request and checked
// on another, and a backend scaled to two replicas would compare two clocks. Rejecting a
// state because two machines disagree by a second would look exactly like a CSRF attack in
// the logs and be impossible to reproduce.
const OAUTH_STATE_CLOCK_SKEW_MS = 60 * 1000;

// Bezpieczne generowanie i weryfikacja stanu OAuth (stateless)
// `salt` is normally random; startBrowserBoundOAuthState below passes the hash of the
// browser-binding nonce instead, which puts that hash under the HMAC without changing the
// state format. It must not contain ':' (hex never does).
function generateOAuthState(userId, service = 'oura', salt = null) {
// crypto.randomBytes (a CSPRNG) rather than Math.random() (a non-cryptographic PRNG,
// predictable if the generator state is known). The HMAC alone still prevents forging state
// without knowing OAUTH_STATE_SECRET, but the salt/nonce in an anti-CSRF flow should be
// generated by a cryptographically secure generator.
  salt = salt || crypto.randomBytes(16).toString('hex');
  // issuedAt is INSIDE the signed payload, not appended next to it: a timestamp outside the
  // HMAC would be the attacker's to rewrite, which is the same as having no timestamp.
  const issuedAt = Date.now();
  const data = `${userId}:${service}:${issuedAt}:${salt}`;
  const hmac = crypto.createHmac('sha256', OAUTH_STATE_SECRET).update(data).digest('hex');
  return `${data}:${hmac}`;
}

function verifyOAuthState(state) {
  if (!state) return null;
  // The format is userId:service:issuedAt:salt:hmac - but `service` may itself contain
  // colons, so the field count is NOT fixed and the parts must be read from both ends, never
  // by position from the left alone.
  //
  // The `issuedAt` field is newer than the rest of this function. States minted by the
  // previous format (userId:service:salt:hmac) do not verify any more - their HMAC covers a
  // different payload - so a consent screen opened in the seconds before a deploy ends at
  // /?google_error=csrf_failed and the user simply clicks the button again. That was accepted
  // deliberately: the alternative, accepting unstamped states "for compatibility", would keep
  // the eternal-state hole open for exactly as long as anyone still held one, which is for
  // ever, because nothing expires them.
  //
  // This is the bug that made "Sign in with Google" impossible to complete. routes/auth.js
  // binds the sign-in state to the client by passing `google_login:<sha256 fingerprint>` as
  // the service, which makes the state FIVE colon-separated fields instead of four. The old
  // `if (parts.length === 4)` check simply fell through for every one of them, so
  // verifyOAuthState returned null on every legitimate callback and the flow ended at
  // `/?google_error=csrf_failed` - a CSRF rejection of the application's own state. The
  // account-linking flow (service 'google_link', no colon) kept working, which is why this
  // looked like "Google sign-in is broken" rather than "state verification is broken".
  //
  // Reading userId from the front and salt/hmac from the back keeps every state that
  // generateOAuthState can produce verifiable, whatever the service string contains, and
  // stays compatible with the four-field states already in flight.
  const parts = state.split(':');
  if (parts.length >= 5) {
    const userId = parts[0];
    const service = parts.slice(1, -3).join(':');
    const issuedAt = parts[parts.length - 3];
    const salt = parts[parts.length - 2];
    const hmac = parts[parts.length - 1];
    const expectedHmac = crypto.createHmac('sha256', OAUTH_STATE_SECRET).update(`${userId}:${service}:${issuedAt}:${salt}`).digest('hex');
  // Bug fix: comparing HMACs with `===` compares the strings byte by byte and stops at the
  // first difference, which in theory leaks through response timing how many leading
  // characters match the expected HMAC (a timing attack) - the same class of risk the rest of
  // this file deliberately guards against (see the CSPRNG comment in generateOAuthState).
  // crypto.timingSafeEqual compares in constant time; it requires buffers of equal length, so
  // we compare the length first (the length of a SHA-256 HMAC in hex is fixed and not a
  // secret).
    const hmacBuf = Buffer.from(hmac, 'utf8');
    const expectedBuf = Buffer.from(expectedHmac, 'utf8');
    const hmacValid = hmacBuf.length === expectedBuf.length && crypto.timingSafeEqual(hmacBuf, expectedBuf);
    if (hmacValid) {
      // The age check runs only AFTER the signature has been verified, so a caller cannot
      // learn anything from the difference between "too old" and "not signed by us" - both
      // return null, and an unsigned state never reaches the clock at all.
      const issuedAtMs = /^\d+$/.test(issuedAt) ? Number(issuedAt) : NaN;
      if (!Number.isFinite(issuedAtMs)) return null;
      const ageMs = Date.now() - issuedAtMs;
      if (ageMs > OAUTH_STATE_MAX_AGE_MS || ageMs < -OAUTH_STATE_CLOCK_SKEW_MS) return null;
      return { userId: parseInt(userId, 10), service, issuedAt: issuedAtMs, salt };
    }
  }
  return null;
}

// Minimal cookie reader. cookie-parser is not a dependency of this project and the
// project deliberately keeps its dependency surface small (see CLAUDE.md); one header,
// parsed once, does not justify a package.
function readCookie(req, name) {
  const header = req.headers.cookie;
  if (!header) return null;
  for (const part of header.split(';')) {
    const eq = part.indexOf('=');
    if (eq === -1) continue;
    if (part.slice(0, eq).trim() === name) {
      try {
        return decodeURIComponent(part.slice(eq + 1).trim());
      } catch {
        return null;
      }
    }
  }
  return null;
}

function sha256Hex(value) {
  return crypto.createHash('sha256').update(value).digest('hex');
}

// ===== Binding a connect/link flow to the browser that started it =====
// The signed state of the Oura / Withings / Google Fit / Google-link flows used to bind only
// a userId. It proved "this backend minted it for user X", not "the browser now arriving at
// the callback is user X's": an attacker could start the flow for their OWN account, stop
// at the provider's consent screen and send that URL to a victim. The victim saw a genuine
// "Dietetyk AI wants access" screen, approved it, and the callback stored the VICTIM's
// Google Fit / Oura tokens on the ATTACKER's account (who could then read the victim's
// activity), or - in the Google-link variant - pinned the victim's Google identity to the
// attacker's account, so the victim's next "Sign in with Google" landed in the attacker's
// account. The state was also valid for ten minutes and reusable within them.
//
// Same remedy as the Google sign-in flow in routes/auth.js: a random nonce in a short-lived
// HttpOnly cookie set on the response that starts the flow, its SHA-256 in the signed state
// (as the salt), and a callback that accepts the state only alongside the matching cookie.
// Only the browser that started the flow holds the cookie, and the callback clears it, so a
// state is also good for exactly one callback.
//
// Path '/api/auth' rather than one callback path: a Withings flow can come back to either
// /api/auth/withings/callback or /api/auth/oura/callback (see resolveWithingsRedirectUri in
// routes/integrations.js). SameSite=Lax is what lets the cookie ride the provider's top-level
// GET redirect back to us. A Withings "custom redirect URI" pointing at ANOTHER host can no
// longer complete the flow - that host never sees this cookie - which is the price of the
// binding.
const OAUTH_BINDING_COOKIE = 'dai_oauth_binding';
const usedBoundStates = new Map(); // salt (= nonce hash) -> forget-after timestamp
const OAUTH_BINDING_COOKIE_PATH = '/api/auth';

function isSecureRequest(req) {
  return !!(req.secure || req.headers['x-forwarded-proto'] === 'https');
}

function startBrowserBoundOAuthState(req, res, userId, service) {
  const nonce = crypto.randomBytes(32).toString('hex');
  res.cookie(OAUTH_BINDING_COOKIE, nonce, {
    httpOnly: true,
    sameSite: 'lax',
    secure: isSecureRequest(req),
    maxAge: OAUTH_STATE_MAX_AGE_MS,
    path: OAUTH_BINDING_COOKIE_PATH
  });
  return generateOAuthState(userId, service, sha256Hex(nonce));
}

// Returns the verified state ({ userId, service, ... }) only when it is signed, fresh AND was
// started by this browser; null otherwise. Always clears the binding cookie it was handed, so
// a callback - accepted or rejected - cannot be replayed with the same state.
function verifyBrowserBoundOAuthState(req, res, state) {
  const nonce = readCookie(req, OAUTH_BINDING_COOKIE);
  if (nonce) {
    res.clearCookie(OAUTH_BINDING_COOKIE, { path: OAUTH_BINDING_COOKIE_PATH });
  }
  const verified = verifyOAuthState(state);
  if (!verified || !nonce) return null;
  const expected = Buffer.from(sha256Hex(nonce), 'utf8');
  const actual = Buffer.from(String(verified.salt), 'utf8');
  if (expected.length !== actual.length || !crypto.timingSafeEqual(expected, actual)) return null;

  // Clearing the cookie makes the state single-use for a well-behaved browser; this makes it
  // single-use, full stop, for anyone who kept a copy of both. Entries only need to outlive
  // the state itself.
  const now = Date.now();
  for (const [salt, expiresAt] of usedBoundStates) {
    if (expiresAt <= now) usedBoundStates.delete(salt);
  }
  if (usedBoundStates.has(verified.salt)) return null;
  usedBoundStates.set(verified.salt, now + OAUTH_STATE_MAX_AGE_MS + OAUTH_STATE_CLOCK_SKEW_MS);
  return verified;
}

// Which refresh failures mean "this authorisation is dead, delete the stored token".
//
// This used to be ANY 4xx, and deleting the token is not a cheap mistake: the integration is
// silently disconnected and the user has to notice and go through the consent screen again.
// Two ordinary situations hit it. A 429 from Oura (rate limit, transient by definition) wiped
// the token. And a refresh race: Oura and Withings ROTATE the refresh token, so when two
// refreshes run at once (the "Sync" button pressed during the hourly sync, or two pods during
// a rollout) the second one presents an already-used refresh token, gets a 4xx - and used to
// delete the fresh token the first one had just stored.
//
// The OAuth 2.0 spec (RFC 6749 section 5.2) reserves `invalid_grant` for exactly "the refresh
// token is invalid, expired or revoked", returned with 400 (some providers use 401). Anything
// else - 429, 5xx, invalid_client from a mistyped secret the user can still fix - keeps the
// token and is retried on the next sync. The race itself is closed by the in-flight map below;
// this check is the second line for the cross-process case it cannot see.
function isRevokedGrant(status, bodyText) {
  return (status === 400 || status === 401) && /invalid_grant/i.test(bodyText || '');
}

// One refresh per (user, service) at a time inside this process - see isRevokedGrant above
// for what two concurrent refreshes of a rotating refresh token do. A second caller arriving
// while the first is in flight gets the same Promise, and therefore the same new token,
// instead of spending the refresh token a second time.
const inFlightTokenLoads = new Map();

function getOrRefreshToken(userId, service) {
  const key = `${userId}:${service}`;
  const pending = inFlightTokenLoads.get(key);
  if (pending) return pending;
  const load = loadOrRefreshToken(userId, service).finally(() => {
    inFlightTokenLoads.delete(key);
  });
  inFlightTokenLoads.set(key, load);
  return load;
}

// Fetching and refreshing an OAuth token
async function loadOrRefreshToken(userId, service) {
  const token = await db.get(`SELECT * FROM oauth_tokens WHERE user_id = ? AND service = ?`, [userId, service]);
  if (!token) return null;
  // Decrypt immediately after reading - the rest of the function below treats
  // token.access_token/refresh_token as if they had always been plaintext.
  token.access_token = decrypt(token.access_token);
  token.refresh_token = decrypt(token.refresh_token);

  const expiresAt = new Date(token.expires_at);
  const now = new Date();

  // If the token is valid for more than 5 minutes, return it as is
  if (expiresAt.getTime() - now.getTime() > 5 * 60 * 1000) {
    return token.access_token;
  }

  console.log(`[OAUTH] Refreshing token for user ${userId}, service: ${service}...`);
  let isPermanentFailure = false;

  try {
    if (service === 'oura') {
      const clientId = await getUserSetting(userId, 'oura_client_id');
      const clientSecret = await getUserSetting(userId, 'oura_client_secret');
      if (!clientId || !clientSecret) {
        isPermanentFailure = true;
        throw new Error('Brak Client ID lub Secret dla Oura.');
      }

      const response = await fetchWithTimeout('https://api.ouraring.com/oauth/token', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          grant_type: 'refresh_token',
          refresh_token: token.refresh_token,
          client_id: clientId,
          client_secret: clientSecret
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        if (isRevokedGrant(response.status, errorText)) {
          isPermanentFailure = true;
        }
        throw new Error(`Błąd odświeżania Oura (Status ${response.status}): ${errorText}`);
      }

      const data = await response.json();
      const newExpiresAt = new Date(Date.now() + data.expires_in * 1000).toISOString();
      await db.run(`
        UPDATE oauth_tokens
        SET access_token = ?, refresh_token = ?, expires_at = ?
        WHERE user_id = ? AND service = 'oura'
      `, [encrypt(data.access_token), encrypt(data.refresh_token || token.refresh_token), newExpiresAt, userId]);

      return data.access_token;
    } else if (service === 'withings') {
      const clientId = await getUserSetting(userId, 'withings_client_id');
      const clientSecret = await getUserSetting(userId, 'withings_client_secret');
      if (!clientId || !clientSecret) {
        isPermanentFailure = true;
        throw new Error('Brak Client ID lub Secret dla Withings.');
      }

      const response = await fetchWithTimeout('https://wbsapi.withings.net/v2/oauth2', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          action: 'requesttoken',
          grant_type: 'refresh_token',
          client_id: clientId,
          client_secret: clientSecret,
          refresh_token: token.refresh_token
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        if (isRevokedGrant(response.status, errorText)) {
          isPermanentFailure = true;
        }
        throw new Error(`Błąd odświeżania Withings (Status ${response.status}): ${errorText}`);
      }

      const resJson = await response.json();
      if (resJson.status !== 0) {
      // Withings error statuses: 100 (invalid token), 200 (invalid client) and so on.
      // Transient errors (503 or 601) are excluded - for those we do not delete the token.
        if (resJson.status === 100 || resJson.status === 200 || resJson.status === 501) {
          isPermanentFailure = true;
        }
        throw new Error(`Błąd Withings API: ${resJson.error || 'Status ' + resJson.status}`);
      }

      const data = resJson.body;
      const newExpiresAt = new Date(Date.now() + data.expires_in * 1000).toISOString();
      await db.run(`
        UPDATE oauth_tokens
        SET access_token = ?, refresh_token = ?, expires_at = ?
        WHERE user_id = ? AND service = 'withings'
      `, [encrypt(data.access_token), encrypt(data.refresh_token || token.refresh_token), newExpiresAt, userId]);

      return data.access_token;
    } else if (service === 'google_fit') {
      const clientId = await getAppConfig('google_client_id');
      const clientSecret = await getAppConfig('google_client_secret');
      if (!clientId || !clientSecret) {
        isPermanentFailure = true;
        throw new Error('Brak Client ID lub Secret dla Google (konfiguracja globalna).');
      }

      const response = await fetchWithTimeout('https://oauth2.googleapis.com/token', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          grant_type: 'refresh_token',
          refresh_token: token.refresh_token,
          client_id: clientId,
          client_secret: clientSecret
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        if (isRevokedGrant(response.status, errorText)) {
          isPermanentFailure = true;
        }
        throw new Error(`Błąd odświeżania Google Fit (Status ${response.status}): ${errorText}`);
      }

      const data = await response.json();
      const newExpiresAt = new Date(Date.now() + data.expires_in * 1000).toISOString();
      await db.run(`
        UPDATE oauth_tokens
        SET access_token = ?, refresh_token = ?, expires_at = ?
        WHERE user_id = ? AND service = 'google_fit'
      `, [encrypt(data.access_token), encrypt(data.refresh_token || token.refresh_token), newExpiresAt, userId]);

      return data.access_token;
    }
  } catch (err) {
    console.error(`[OAUTH ERROR] Failed to refresh the token for ${service} (user ${userId}):`, err.message);
    if (isPermanentFailure) {
      console.warn(`[OAUTH] Deleting the invalid token from the database for ${service} (user ${userId}) because the authorisation is permanently invalid.`);
      await db.run(`DELETE FROM oauth_tokens WHERE user_id = ? AND service = ?`, [userId, service]);
    } else {
      console.log(`[OAUTH] Keeping the token for ${service} (user ${userId}) in the database - the error looks transient.`);
    }
    return null;
  }
  return null;
}

module.exports = {
  getAppConfig,
  getUserSetting,
  generateOAuthState,
  verifyOAuthState,
  getOrRefreshToken,
  readCookie,
  isSecureRequest,
  startBrowserBoundOAuthState,
  verifyBrowserBoundOAuthState,
  OAUTH_STATE_MAX_AGE_MS
};
