const crypto = require('crypto');
const db = require('../db');
const { fetchWithTimeout } = require('../utils/fetchWithTimeout');
const { encrypt, decrypt } = require('../utils/encryption');

// Secret used to sign (HMAC) the `state` parameter in the OAuth flow.
// Previously, if APP_PASSWORD was missing from the environment the code silently fell back
// to a fixed string 'default_secret' that is visible in the source - which would make the
// signature trivial to forge (a CSRF attack on the OAuth flow) after a .env misconfiguration
// in production. Now a missing configuration is a startup error (fail-fast), so such a
// mistake can never pass unnoticed.
// It can be overridden with a dedicated OAUTH_STATE_SECRET variable, so the admin panel
// password (APP_PASSWORD) need not double as a cryptographic secret.
const OAUTH_STATE_SECRET = process.env.OAUTH_STATE_SECRET || process.env.APP_PASSWORD;
if (!OAUTH_STATE_SECRET) {
  throw new Error(
    'Brak OAUTH_STATE_SECRET (lub zapasowo APP_PASSWORD) w zmiennych środowiskowych. ' +
    'Ustaw jedną z nich w backend/.env, inaczej przepływ OAuth (Oura/Withings/Google) nie jest bezpieczny.'
  );
}

// Helper for reading configuration from the app_config table. decrypt() is safe to call for
// EVERY key, not only the secret ones in APP_SECRET_CONFIG_KEYS - for values never encrypted
// by encrypt() (see utils/encryption.js) it is
// a no-op, because they lack the recognisable prefix.
async function getAppConfig(key) {
  if (key === 'app_url' && process.env.APP_URL) {
    return process.env.APP_URL;
  }
  const row = await db.get(`SELECT value FROM app_config WHERE key = ?`, [key]);
  return row ? decrypt(row.value) : null;
}

// Helper for reading a specific user's settings - decrypt() as above, safe for non-secret
// values (a no-op without the enc:v1: prefix).
async function getUserSetting(userId, key) {
  const row = await db.get(`SELECT value FROM settings WHERE user_id = ? AND key = ?`, [userId, key]);
  return row ? decrypt(row.value) : null;
}

// Session token verification for the OAuth routes that INITIATE a connection
// (Oura/Withings/Google Fit/Google link) and receive the token through ?token= in the query
// string, because they are reached by a top-level navigation rather than a fetch with an
// Authorization header (see the comment in middleware/auth.js). Those routes are on
// requireAuth's exception list, so they are responsible for full verification themselves -
// and they used to check ONLY that the session token was valid, without checking whether a
// user with 2FA enabled had actually completed the code verification (a temporary session
// with is_verified_2fa=0 and a short TTL could in theory initiate linking an external
// account). This function replicates exactly the same checks requireAuth applies to routes
// behind the Authorization header, so both paths offer the same level of security.
async function getVerifiedSessionByToken(token) {
  if (!token) return null;
  const session = await db.get(`
    SELECT s.user_id, s.expires_at, s.is_verified_2fa, u.totp_enabled
    FROM sessions s
    JOIN users u ON s.user_id = u.id
    WHERE s.token = ?
  `, [token]);

  if (!session) return null;
  if (new Date(session.expires_at.replace(' ', 'T') + 'Z') < new Date()) return null;
  if (session.totp_enabled === 1 && session.is_verified_2fa === 0) return null;

  return session;
}

// Safe generation and verification of the OAuth state (stateless)
function generateOAuthState(userId, service = 'oura') {
// crypto.randomBytes (a CSPRNG) rather than Math.random() (a non-cryptographic PRNG,
// predictable if the generator state is known). The HMAC alone still prevents forging state
// without knowing OAUTH_STATE_SECRET, but the salt/nonce in an anti-CSRF flow should be
// generated by a cryptographically secure generator.
  const salt = crypto.randomBytes(16).toString('hex');
  const data = `${userId}:${service}:${salt}`;
  const hmac = crypto.createHmac('sha256', OAUTH_STATE_SECRET).update(data).digest('hex');
  return `${userId}:${service}:${salt}:${hmac}`;
}

function verifyOAuthState(state) {
  if (!state) return null;
  // The current format is always four parts (userId:service:salt:hmac), produced solely by
  // generateOAuthState above. The dead branch handling the old three-part format
  // (userId:salt:hmac, with a default service='oura') was removed - no current state
  // generator produces it any more.
  const parts = state.split(':');
  if (parts.length === 4) {
    const [userId, service, salt, hmac] = parts;
    const expectedHmac = crypto.createHmac('sha256', OAUTH_STATE_SECRET).update(`${userId}:${service}:${salt}`).digest('hex');
  // Bug fix: comparing HMACs with `===` compares the strings byte by byte and stops at the
  // first difference, which in theory leaks through response timing how many leading
  // characters match the expected HMAC (a timing attack) - the same class of risk the rest of
  // this file deliberately guards against (see the CSPRNG comment in generateOAuthState).
  // crypto.timingSafeEqual compares in constant time; it requires buffers of equal length, so
  // we compare the length first (the length of a SHA-256 HMAC in hex is fixed and not a
  // secret).
    const hmacBuf = Buffer.from(hmac, 'utf8');
    const expectedBuf = Buffer.from(expectedHmac, 'utf8');
    const hmacValid = hmacBuf.length === expectedBuf.length && crypto.timingSafeEqual(hmacBuf, expectedBuf);
    if (hmacValid) {
      return { userId: parseInt(userId, 10), service };
    }
  }
  return null;
}

// Fetching and refreshing an OAuth token
async function getOrRefreshToken(userId, service) {
  const token = await db.get(`SELECT * FROM oauth_tokens WHERE user_id = ? AND service = ?`, [userId, service]);
  if (!token) return null;
  // Decrypt immediately after reading - the rest of the function below treats
  // token.access_token/refresh_token as if they had always been plaintext.
  token.access_token = decrypt(token.access_token);
  token.refresh_token = decrypt(token.refresh_token);

  const expiresAt = new Date(token.expires_at);
  const now = new Date();

  // If the token is valid for more than 5 minutes, return it as is
  if (expiresAt.getTime() - now.getTime() > 5 * 60 * 1000) {
    return token.access_token;
  }

  console.log(`[OAUTH] Refreshing token for user ${userId}, service: ${service}...`);
  let isPermanentFailure = false;

  try {
    if (service === 'oura') {
      const clientId = await getUserSetting(userId, 'oura_client_id');
      const clientSecret = await getUserSetting(userId, 'oura_client_secret');
      if (!clientId || !clientSecret) {
        isPermanentFailure = true;
        throw new Error('Brak Client ID lub Secret dla Oura.');
      }

      const response = await fetchWithTimeout('https://api.ouraring.com/oauth/token', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          grant_type: 'refresh_token',
          refresh_token: token.refresh_token,
          client_id: clientId,
          client_secret: clientSecret
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        if (response.status >= 400 && response.status < 500) {
          isPermanentFailure = true;
        }
        throw new Error(`Błąd odświeżania Oura (Status ${response.status}): ${errorText}`);
      }

      const data = await response.json();
      const newExpiresAt = new Date(Date.now() + data.expires_in * 1000).toISOString();
      await db.run(`
        UPDATE oauth_tokens
        SET access_token = ?, refresh_token = ?, expires_at = ?
        WHERE user_id = ? AND service = 'oura'
      `, [encrypt(data.access_token), encrypt(data.refresh_token || token.refresh_token), newExpiresAt, userId]);

      return data.access_token;
    } else if (service === 'withings') {
      const clientId = await getUserSetting(userId, 'withings_client_id');
      const clientSecret = await getUserSetting(userId, 'withings_client_secret');
      if (!clientId || !clientSecret) {
        isPermanentFailure = true;
        throw new Error('Brak Client ID lub Secret dla Withings.');
      }

      const response = await fetchWithTimeout('https://wbsapi.withings.net/v2/oauth2', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          action: 'requesttoken',
          grant_type: 'refresh_token',
          client_id: clientId,
          client_secret: clientSecret,
          refresh_token: token.refresh_token
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        if (response.status >= 400 && response.status < 500) {
          isPermanentFailure = true;
        }
        throw new Error(`Błąd odświeżania Withings (Status ${response.status}): ${errorText}`);
      }

      const resJson = await response.json();
      if (resJson.status !== 0) {
      // Withings error statuses: 100 (invalid token), 200 (invalid client) and so on.
      // Transient errors (503 or 601) are excluded - for those we do not delete the token.
        if (resJson.status === 100 || resJson.status === 200 || resJson.status === 501) {
          isPermanentFailure = true;
        }
        throw new Error(`Błąd Withings API: ${resJson.error || 'Status ' + resJson.status}`);
      }

      const data = resJson.body;
      const newExpiresAt = new Date(Date.now() + data.expires_in * 1000).toISOString();
      await db.run(`
        UPDATE oauth_tokens
        SET access_token = ?, refresh_token = ?, expires_at = ?
        WHERE user_id = ? AND service = 'withings'
      `, [encrypt(data.access_token), encrypt(data.refresh_token || token.refresh_token), newExpiresAt, userId]);

      return data.access_token;
    } else if (service === 'google_fit') {
      const clientId = await getAppConfig('google_client_id');
      const clientSecret = await getAppConfig('google_client_secret');
      if (!clientId || !clientSecret) {
        isPermanentFailure = true;
        throw new Error('Brak Client ID lub Secret dla Google (konfiguracja globalna).');
      }

      const response = await fetchWithTimeout('https://oauth2.googleapis.com/token', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          grant_type: 'refresh_token',
          refresh_token: token.refresh_token,
          client_id: clientId,
          client_secret: clientSecret
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        if (response.status >= 400 && response.status < 500) {
          isPermanentFailure = true;
        }
        throw new Error(`Błąd odświeżania Google Fit (Status ${response.status}): ${errorText}`);
      }

      const data = await response.json();
      const newExpiresAt = new Date(Date.now() + data.expires_in * 1000).toISOString();
      await db.run(`
        UPDATE oauth_tokens
        SET access_token = ?, refresh_token = ?, expires_at = ?
        WHERE user_id = ? AND service = 'google_fit'
      `, [encrypt(data.access_token), encrypt(data.refresh_token || token.refresh_token), newExpiresAt, userId]);

      return data.access_token;
    }
  } catch (err) {
    console.error(`[OAUTH ERROR] Failed to refresh the token for ${service} (user ${userId}):`, err.message);
    if (isPermanentFailure) {
      console.warn(`[OAUTH] Deleting the invalid token from the database for ${service} (user ${userId}) because the authorisation is permanently invalid.`);
      await db.run(`DELETE FROM oauth_tokens WHERE user_id = ? AND service = ?`, [userId, service]);
    } else {
      console.log(`[OAUTH] Keeping the token for ${service} (user ${userId}) in the database - the error looks transient.`);
    }
    return null;
  }
  return null;
}

module.exports = {
  getAppConfig,
  getUserSetting,
  generateOAuthState,
  verifyOAuthState,
  getOrRefreshToken,
  getVerifiedSessionByToken
};
