const express = require('express');
const router = express.Router();
const db = require('../db');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const { authenticator } = require('otplib');
const QRCode = require('qrcode');
const { sendWeeklySummaryForUser, sendDailySummaryForUser, sendMonthlySummaryForUser } = require('../services/summaries');
const { buildHealthReportPdf } = require('../services/pdfReport');
const { createShareLink, listSharesForUser, revokeShare, VALIDITY_OPTIONS_HOURS } = require('../services/sharedReports');
const { getAppConfig } = require('../services/oauthHelpers');
const { summaryEmailLimiter } = require('../middleware/rateLimit');
const { USER_SECRET_SETTING_KEYS, maskSecretValue, isMaskedSecretWrite } = require('../utils/secretKeys');
const { encrypt } = require('../utils/encryption');
const { geocodeLocation } = require('../utils/weatherContext');

// Simple email format validation (not full RFC 5322 - this is enough to reject obviously
// invalid values written straight to the database or used as a Mailgun recipient).
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
// Time format HH:MM (00-23 : 00-59), used when scheduling summary delivery.
const TIME_REGEX = /^([01]\d|2[0-3]):([0-5]\d)$/;
// sync_token validation (round 15 audit fix): the token is generated by default as
// 'sync_' + 24 random hex bytes (see routes/auth.js and admin.js), but the endpoint below
// lets a user overwrite it with a value of their own. sync_token is the ONLY secret
// authorising the unauthenticated Apple Health webhook
// (POST /api/integrations/apple-health/:syncToken, see routes/appleHealth.js and
// server.js - that endpoint deliberately bypasses requireAuth). Without a minimum length
// and format a user could set a token such as 'abc', which in practice would make the
// webhook publicly guessable and hijackable.
const SYNC_TOKEN_REGEX = /^[A-Za-z0-9_-]{16,128}$/;
// Length limit for the physique goal description - without it nothing bounded the size of
// the text that later goes into the Gemini prompt (see dashboard.js and chat.js),
// analogicznie do MAX_CHAT_MESSAGE_LENGTH w chat.js.
const MAX_BODY_GOAL_TEXT_LENGTH = 1000;
// Size limit for the physique goal photo as base64 (about 3 MB encoded, roughly 2.2 MB of
// real file) - the photo is compressed and scaled on the frontend (see Settings.jsx), but
// this is the only real protection against someone posting straight to the API.
const MAX_BODY_GOAL_PHOTO_LENGTH = 4 * 1024 * 1024;
// Avatar size limit - same reasoning as the physique goal photo above. The
// POST /api/user/profile endpoint used to store `avatar` with NO size validation at all;
// the only protection was the global express.json({limit:'20mb'}) in server.js.
const MAX_AVATAR_BASE64_LENGTH = 3 * 1024 * 1024;
// Length limit for the location query (Settings -> weather location) - the query goes to
// the external Open-Meteo geocoder, so bound its size rather than passing an arbitrarily
// long string through (see GET /api/settings/geocode-location below).
const MAX_LOCATION_QUERY_LENGTH = 100;

router.get('/api/settings', async (req, res) => {
  try {
    const rows = await db.all(`SELECT * FROM settings WHERE user_id = ?`, [req.user.id]);
    const user = await db.get(`SELECT sync_token FROM users WHERE id = ?`, [req.user.id]);
    const settings = {
      sync_token: user ? user.sync_token : ''
    };
    rows.forEach(r => {
      if (USER_SECRET_SETTING_KEYS.includes(r.key) && r.value) {
        settings[r.key] = maskSecretValue(r.key, r.value, USER_SECRET_SETTING_KEYS);
      } else if (r.value === '') {
      // NOTE: Number('') === 0 and isNaN('') === false - so without this exception an empty
      // string would be converted to the number 0 here. That was a real bug:
      // withings_client_id/oura_client_id stored as '' (through an unintended empty save of
      // the whole settings form, for instance) came back from this endpoint as 0. In JS 0 is
      // a number, so the code building the OAuth URL - which only checks `if (!clientId)` -
      // rejected it; but the string "0", once saved back through POST, is no longer falsy and
      // passed through, producing client_id=0 in the Withings/Oura authorisation URL.
        settings[r.key] = '';
      } else {
        settings[r.key] = isNaN(r.value) ? r.value : Number(r.value);
      }
    });
    // Note: there is NO fallback to global environment variables (OURA_CLIENT_ID/SECRET,
    // WITHINGS_CLIENT_ID/SECRET) - every user, admin included, must configure their own Oura
    // and Withings application credentials. That way a new user never connects through
    // another user's OAuth application.
    res.json(settings);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Błąd pobierania ustawień.' });
  }
});

// 6. Saving settings and daily targets
// Integration credential fields must never be overwritten with empty or zero values,
// because that breaks OAuth (see the comment on GET /api/settings above). Every settings
// save from the frontend sends the WHOLE form state, not just the changed field, so saving
// only the calorie targets could otherwise
// accidentally 'clear' the Client ID/Secret when the form state happened to hold them
// empty or unset at that moment.
const CREDENTIAL_KEYS = ['oura_client_id', 'oura_client_secret', 'withings_client_id', 'withings_client_secret'];

router.post('/api/settings', async (req, res) => {
  const settings = req.body; // keys and values
  try {
    for (const [key, val] of Object.entries(settings)) {
      if (key === 'sync_token') continue; // Pole tylko do odczytu
      if (isMaskedSecretWrite(key, val, USER_SECRET_SETTING_KEYS)) {
        continue; // skip updating a secret when the mask was sent back
      }
      if (CREDENTIAL_KEYS.includes(key) && (val === '' || val === null || val === undefined || val === 0)) {
        continue; // never store an empty/zero credential value - see the comment above
      }
      // Sekrety (gemini_api_key, oura/withings_client_secret) trzymamy w bazie
      // encrypted (see utils/encryption.js) - encrypt() is a no-op for the remaining,
      // non-secret settings keys.
      const storedValue = USER_SECRET_SETTING_KEYS.includes(key) ? encrypt(String(val)) : String(val);
      await db.run(`
        INSERT INTO settings (user_id, key, value)
        VALUES (?, ?, ?)
        ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
      `, [req.user.id, key, storedValue]);
    }
    res.json({ success: true, message: 'Ustawienia zostały zaktualizowane.' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Błąd zapisu ustawień.' });
  }
});

// Location lookup for the 'Location' field in Settings (the weather context injected into
// AI prompts - see utils/weatherContext.js). Returns a list of candidates for the frontend
// to choose from (Open-Meteo Geocoding, no API key required) - place names are often
// ambiguous, so we do NOT auto-select the first result. Choosing the location itself (POST)
// goes through the existing settings endpoint, since weather_location_label and friends are
// ordinary keys in the settings table - this endpoint only searches and stores nothing.
router.get('/api/settings/geocode-location', async (req, res) => {
  const query = typeof req.query.q === 'string' ? req.query.q.trim() : '';
  if (!query) {
    return res.status(400).json({ error: 'Podaj nazwę miejscowości.' });
  }
  if (query.length > MAX_LOCATION_QUERY_LENGTH) {
    return res.status(400).json({ error: `Zapytanie jest zbyt długie (maks. ${MAX_LOCATION_QUERY_LENGTH} znaków).` });
  }
  try {
    const results = await geocodeLocation(query);
    res.json({ results });
  } catch (err) {
    console.error('[GEOCODING ERROR]', err);
    res.status(502).json({ error: 'Błąd wyszukiwania lokalizacji (usługa geokodowania jest chwilowo niedostępna).' });
  }
});

// 6a. Fetch the user profile (name, email, avatar, role and 2FA status)
router.get('/api/user/profile', async (req, res) => {
  try {
    const user = await db.get(`SELECT username, email, avatar_base64, role, totp_enabled, first_name, last_name, google_id, birth_year, body_goal_text, body_goal_photo_base64 FROM users WHERE id = ?`, [req.user.id]);
    if (!user) {
      return res.status(404).json({ error: 'Użytkownik nie istnieje.' });
    }

    const summaryEnabledRow = await db.get(`SELECT value FROM settings WHERE user_id = ? AND key = 'weekly_summary_enabled'`, [req.user.id]);
    const summaryDayRow = await db.get(`SELECT value FROM settings WHERE user_id = ? AND key = 'weekly_summary_day'`, [req.user.id]);
    const summaryTimeRow = await db.get(`SELECT value FROM settings WHERE user_id = ? AND key = 'weekly_summary_time'`, [req.user.id]);

    const monthlyEnabledRow = await db.get(`SELECT value FROM settings WHERE user_id = ? AND key = 'monthly_summary_enabled'`, [req.user.id]);
    const monthlyDayRow = await db.get(`SELECT value FROM settings WHERE user_id = ? AND key = 'monthly_summary_day'`, [req.user.id]);
    const monthlyTimeRow = await db.get(`SELECT value FROM settings WHERE user_id = ? AND key = 'monthly_summary_time'`, [req.user.id]);
    const langRow = await db.get(`SELECT value FROM settings WHERE user_id = ? AND key = 'language'`, [req.user.id]);

    const hasOuraRow = await db.get(`SELECT 1 FROM oauth_tokens WHERE user_id = ? AND service = 'oura'`, [req.user.id]);
    const hasWithingsRow = await db.get(`SELECT 1 FROM oauth_tokens WHERE user_id = ? AND service = 'withings'`, [req.user.id]);
    const hasGoogleFitRow = await db.get(`SELECT 1 FROM oauth_tokens WHERE user_id = ? AND service = 'google_fit'`, [req.user.id]);

    res.json({
      username: user.username,
      email: user.email || '',
      avatar_base64: user.avatar_base64,
      role: user.role,
      first_name: user.first_name || '',
      last_name: user.last_name || '',
      // birth_year is a number, or missing - unlike first_name/last_name we do NOT turn a
      // missing value into an empty string, so the frontend can tell 'not set' apart
      birth_year: user.birth_year || null,
      // Physique goal (text description plus an optional reference photo) - see the
      // migration in db.js. A missing value is an empty string or null, matching the other
      // optional profile fields above.
      body_goal_text: user.body_goal_text || '',
      body_goal_photo_base64: user.body_goal_photo_base64 || null,
      totp_enabled: user.totp_enabled === 1,
      weekly_summary_enabled: summaryEnabledRow ? summaryEnabledRow.value === '1' : false,
      weekly_summary_day: summaryDayRow ? Number(summaryDayRow.value) : 1,
      weekly_summary_time: summaryTimeRow ? summaryTimeRow.value : '18:00',
      monthly_summary_enabled: monthlyEnabledRow ? monthlyEnabledRow.value === '1' : false,
      monthly_summary_day: monthlyDayRow ? Number(monthlyDayRow.value) : 1,
      monthly_summary_time: monthlyTimeRow ? monthlyTimeRow.value : '09:00',
      language: langRow ? langRow.value : 'pl',
      has_oura: !!hasOuraRow,
      has_withings: !!hasWithingsRow,
      has_google: !!user.google_id,
      has_google_fit: !!hasGoogleFitRow
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Błąd pobierania profilu.' });
  }
});

// 6b. Update the user profile (avatar, email, syncToken)
router.post('/api/user/profile', async (req, res) => {
  const { avatar, email, syncToken, first_name, last_name, birth_year, weekly_summary_enabled, weekly_summary_day, weekly_summary_time, monthly_summary_enabled, monthly_summary_day, monthly_summary_time, body_goal_text, body_goal_photo, target_weight_kg, target_body_fat_pct } = req.body;
  try {
    if (syncToken !== undefined) {
      const trimmedToken = syncToken.trim();
      if (!trimmedToken) {
        return res.status(400).json({ error: 'Token synchronizacji nie może być pusty.' });
      }
      if (!SYNC_TOKEN_REGEX.test(trimmedToken)) {
        return res.status(400).json({ error: 'Token synchronizacji musi mieć 16-128 znaków (litery, cyfry, "_" lub "-").' });
      }
      const existing = await db.get(`SELECT id FROM users WHERE sync_token = ? AND id != ?`, [trimmedToken, req.user.id]);
      if (existing) {
        return res.status(400).json({ error: 'Ten token synchronizacji jest już przypisany do innego użytkownika.' });
      }
      await db.run(`UPDATE users SET sync_token = ? WHERE id = ?`, [trimmedToken, req.user.id]);
    }

      // Email format validation - this field is later used as the default Mailgun recipient
      // for summaries, so an obviously invalid value should not reach the database.
    if (email !== undefined && email !== '' && !EMAIL_REGEX.test(email)) {
      return res.status(400).json({ error: 'Niepoprawny format adresu e-mail.' });
    }

    if (avatar !== undefined && avatar !== null && avatar.length > MAX_AVATAR_BASE64_LENGTH) {
      return res.status(400).json({ error: 'Zdjęcie profilowe jest zbyt duże.' });
    }

    if (avatar !== undefined && email !== undefined) {
      await db.run(`UPDATE users SET avatar_base64 = ?, email = ? WHERE id = ?`, [avatar, email, req.user.id]);
    } else if (avatar !== undefined) {
      await db.run(`UPDATE users SET avatar_base64 = ? WHERE id = ?`, [avatar, req.user.id]);
    } else if (email !== undefined) {
      await db.run(`UPDATE users SET email = ? WHERE id = ?`, [email, req.user.id]);
    }

    // First/last name - used by the AI dietician to personalise its phrasing ('Hi Marcin').
    // Trimmed, with an empty string turned into NULL so the model never receives a literally
    // empty string as the user's name.
    if (first_name !== undefined) {
      const trimmedFirstName = String(first_name).trim();
      await db.run(`UPDATE users SET first_name = ? WHERE id = ?`, [trimmedFirstName || null, req.user.id]);
    }
    if (last_name !== undefined) {
      const trimmedLastName = String(last_name).trim();
      await db.run(`UPDATE users SET last_name = ? WHERE id = ?`, [trimmedLastName || null, req.user.id]);
    }

    // Birth year - used by the Dashboard to compute a real HRmax (220 - age) for the cardio
    // zones. An empty string or null means the user is clearing the field, e.g. preferring
    // not to give their age - we then store NULL and the frontend falls back to
    // zahardkodowanego fallbacku. Inaczej wymagamy realnego, sensownego roku.
    if (birth_year !== undefined) {
      if (birth_year === '' || birth_year === null) {
        await db.run(`UPDATE users SET birth_year = ? WHERE id = ?`, [null, req.user.id]);
      } else {
        const birthYearNum = Number(birth_year);
        const isValidBirthYear = Number.isInteger(birthYearNum) && birthYearNum >= 1920 && birthYearNum <= new Date().getFullYear() - 5;
        if (!isValidBirthYear) {
          return res.status(400).json({ error: 'Nieprawidłowy rok urodzenia.' });
        }
        await db.run(`UPDATE users SET birth_year = ? WHERE id = ?`, [birthYearNum, req.user.id]);
      }
    }

    // Cel sylwetki - opis tekstowy. Pusty string/null = czyszczenie pola, tak jak
    // as with the first and last name above. The AI (dashboard.js, chat.js) reads this value
    // every time it generates advice or a chat reply.
    if (body_goal_text !== undefined) {
      const trimmedGoalText = String(body_goal_text || '').trim();
      if (trimmedGoalText.length > MAX_BODY_GOAL_TEXT_LENGTH) {
        return res.status(400).json({ error: `Opis celu sylwetki jest zbyt długi (maks. ${MAX_BODY_GOAL_TEXT_LENGTH} znaków).` });
      }
      await db.run(`UPDATE users SET body_goal_text = ? WHERE id = ?`, [trimmedGoalText || null, req.user.id]);
    }

    // Physique goal - the reference photo. body_goal_photo === null means the photo is being
    // deleted (the same convention as removing an avatar in Settings.jsx).
    if (body_goal_photo !== undefined) {
      if (body_goal_photo === null) {
        await db.run(`UPDATE users SET body_goal_photo_base64 = NULL WHERE id = ?`, [req.user.id]);
      } else {
        if (typeof body_goal_photo !== 'string' || !body_goal_photo.startsWith('data:image/')) {
          return res.status(400).json({ error: 'Nieprawidłowy format zdjęcia.' });
        }
        if (body_goal_photo.length > MAX_BODY_GOAL_PHOTO_LENGTH) {
          return res.status(400).json({ error: 'Zdjęcie jest zbyt duże.' });
        }
        await db.run(`UPDATE users SET body_goal_photo_base64 = ? WHERE id = ?`, [body_goal_photo, req.user.id]);
      }
    }

    if (weekly_summary_enabled !== undefined) {
      await db.run(`
        INSERT INTO settings (user_id, key, value)
        VALUES (?, 'weekly_summary_enabled', ?)
        ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
      `, [req.user.id, weekly_summary_enabled ? '1' : '0']);
    }
    if (weekly_summary_day !== undefined) {
      // scheduler.js interprets weekly_summary_day as a weekday 1-7 (1=Monday..7=Sunday, see
      // currentDay in scheduler.js) - outside that range the weekly summary would simply
      // never be sent (currentDay === scheduledDay never true). That is a silent, hard-to-
      // diagnose broken feature rather than a security hole, but it is worth rejecting
      // outright at the input.
      const dayNum = Number(weekly_summary_day);
      if (!Number.isInteger(dayNum) || dayNum < 1 || dayNum > 7) {
        return res.status(400).json({ error: 'Dzień tygodnia podsumowania musi być liczbą 1-7.' });
      }
      await db.run(`
        INSERT INTO settings (user_id, key, value)
        VALUES (?, 'weekly_summary_day', ?)
        ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
      `, [req.user.id, dayNum]);
    }
    if (weekly_summary_time !== undefined) {
      if (!TIME_REGEX.test(weekly_summary_time)) {
        return res.status(400).json({ error: 'Godzina podsumowania musi być w formacie HH:MM.' });
      }
      await db.run(`
        INSERT INTO settings (user_id, key, value)
        VALUES (?, 'weekly_summary_time', ?)
        ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
      `, [req.user.id, weekly_summary_time]);
    }

    if (monthly_summary_enabled !== undefined) {
      await db.run(`
        INSERT INTO settings (user_id, key, value)
        VALUES (?, 'monthly_summary_enabled', ?)
        ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
      `, [req.user.id, monthly_summary_enabled ? '1' : '0']);
    }
    if (monthly_summary_day !== undefined) {
      // scheduler.js clamps the value to the number of days in the given month anyway,
      // but rejecting anything outside 1-31 at the input is clearer than relying solely on
      // that clamping in the scheduler.
      const monthDayNum = Number(monthly_summary_day);
      if (!Number.isInteger(monthDayNum) || monthDayNum < 1 || monthDayNum > 31) {
        return res.status(400).json({ error: 'Dzień miesiąca podsumowania musi być liczbą 1-31.' });
      }
      await db.run(`
        INSERT INTO settings (user_id, key, value)
        VALUES (?, 'monthly_summary_day', ?)
        ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
      `, [req.user.id, monthDayNum]);
    }
    if (monthly_summary_time !== undefined) {
      if (!TIME_REGEX.test(monthly_summary_time)) {
        return res.status(400).json({ error: 'Godzina podsumowania musi być w formacie HH:MM.' });
      }
      await db.run(`
        INSERT INTO settings (user_id, key, value)
        VALUES (?, 'monthly_summary_time', ?)
        ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
      `, [req.user.id, monthly_summary_time]);
    }

    if (target_weight_kg !== undefined) {
      const numWeight = target_weight_kg === '' ? null : Number(target_weight_kg);
      if (numWeight !== null && (isNaN(numWeight) || numWeight < 30 || numWeight > 200)) {
        return res.status(400).json({ error: 'Waga docelowa musi być liczbą w zakresie 30-200 kg.' });
      }
      await db.run(`
        INSERT INTO settings (user_id, key, value)
        VALUES (?, 'target_weight_kg', ?)
        ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
      `, [req.user.id, numWeight !== null ? String(numWeight) : '']);
    }

    if (target_body_fat_pct !== undefined) {
      const numFat = target_body_fat_pct === '' ? null : Number(target_body_fat_pct);
      if (numFat !== null && (isNaN(numFat) || numFat < 0 || numFat > 60)) {
        return res.status(400).json({ error: 'Docelowy % tłuszczu musi być liczbą w zakresie 0-60%.' });
      }
      await db.run(`
        INSERT INTO settings (user_id, key, value)
        VALUES (?, 'target_body_fat_pct', ?)
        ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
      `, [req.user.id, numFat !== null ? String(numFat) : '']);
    }

    res.json({ success: true, message: 'Profil został zaktualizowany.' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Błąd aktualizacji profilu.' });
  }
});

router.post('/api/user/setup-2fa', async (req, res) => {
  try {
    const user = await db.get(`SELECT username, totp_secret FROM users WHERE id = ?`, [req.user.id]);
    if (!user) {
      return res.status(404).json({ error: 'Użytkownik nie istnieje.' });
    }

    const secret = authenticator.generateSecret();
    await db.run(`UPDATE users SET totp_secret = ? WHERE id = ?`, [secret, req.user.id]);

    const tempToken = 'temp_' + crypto.randomBytes(24).toString('hex');
    const expiresAt = new Date(Date.now() + 5 * 60 * 1000).toISOString().replace('T', ' ').slice(0, 19);

    await db.run(`
      INSERT INTO sessions (token, user_id, expires_at, is_verified_2fa)
      VALUES (?, ?, ?, 0)
    `, [tempToken, req.user.id, expiresAt]);

    const otpauth = authenticator.keyuri(user.username, 'Dietetyk AI', secret);
    const qrCodeDataUrl = await QRCode.toDataURL(otpauth);

    res.json({
      secret,
      qrCode: qrCodeDataUrl,
      tempToken
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Błąd generowania konfiguracji 2FA.' });
  }
});

// 6b-2. Enable 2FA once a logged-in user has verified the code
router.post('/api/user/verify-2fa', async (req, res) => {
  const { tempToken, code } = req.body;
  if (!tempToken || !code) {
    return res.status(400).json({ error: 'Token i kod są wymagane.' });
  }

  try {
    const session = await db.get(`
      SELECT s.*, u.totp_secret
      FROM sessions s
      JOIN users u ON s.user_id = u.id
      WHERE s.token = ? AND s.user_id = ? AND datetime(s.expires_at) > datetime('now')
    `, [tempToken, req.user.id]);

    if (!session) {
      return res.status(400).json({ error: 'Tymczasowa sesja wygasła lub jest niepoprawna. Spróbuj ponownie.' });
    }

    const isValid = authenticator.verify({
      token: code,
      secret: session.totp_secret
    });

    if (!isValid) {
      return res.status(400).json({ error: 'Niepoprawny kod 2FA.' });
    }

    // Activate 2FA for the user
    await db.run(`UPDATE users SET totp_enabled = 1 WHERE id = ?`, [req.user.id]);
    // Remove the temporary session
    await db.run(`DELETE FROM sessions WHERE token = ?`, [tempToken]);

    res.json({ success: true, message: 'Dwuetapowa weryfikacja (2FA) została włączona.' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Błąd aktywacji 2FA.' });
  }
});

// 6b-3. Disable 2FA for a logged-in user.
// NOTE: we require re-verification with the current password before disabling 2FA. Without
// it, merely holding an active logged-in session - a stolen session token, or an unlocked
// device left unattended - was enough to permanently switch off the second factor, with no
// knowledge of the password or a current TOTP code. The same password re-verification
// pattern is already used for changing the password and deleting the account (see above).
router.post('/api/user/disable-2fa', async (req, res) => {
  const { password } = req.body;
  if (!password) {
    return res.status(400).json({ error: 'Wymagane jest podanie aktualnego hasła, aby wyłączyć 2FA.' });
  }
  try {
    const user = await db.get(`SELECT password_hash FROM users WHERE id = ?`, [req.user.id]);
    if (!user) {
      return res.status(404).json({ error: 'Użytkownik nie istnieje.' });
    }

    const isMatch = await bcrypt.compare(password, user.password_hash);
    if (!isMatch) {
      return res.status(400).json({ error: 'Niepoprawne hasło.' });
    }

    await db.run(`UPDATE users SET totp_enabled = 0, totp_secret = NULL WHERE id = ?`, [req.user.id]);
    res.json({ success: true, message: 'Dwuetapowa weryfikacja (2FA) została wyłączona.' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Błąd dezaktywacji 2FA.' });
  }
});

// Unlinking the Google account - password login (or Google Fit, if it was connected only
// alongside Google sign-in) remains available, because the account always has a
// password_hash: random if the account was created through Google, and resettable.
router.post('/api/user/unlink-google', async (req, res) => {
  try {
    await db.run(`UPDATE users SET google_id = NULL WHERE id = ?`, [req.user.id]);
    res.json({ success: true, message: 'Odłączono konto Google.' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Błąd odłączania konta Google.' });
  }
});

// 6c. Change the user's password
router.post('/api/user/change-password', async (req, res) => {
  const { currentPassword, newPassword } = req.body;
  if (!currentPassword || !newPassword) {
    return res.status(400).json({ error: 'Obecne i nowe hasło są wymagane.' });
  }
  if (newPassword.length < 8) {
    return res.status(400).json({ error: 'Hasło musi mieć co najmniej 8 znaków.' });
  }
  if (!/[a-zA-Z]/.test(newPassword) || !/[0-9]/.test(newPassword)) {
    return res.status(400).json({ error: 'Hasło musi zawierać co najmniej jedną literę i jedną cyfrę.' });
  }

  try {
    const user = await db.get(`SELECT password_hash FROM users WHERE id = ?`, [req.user.id]);
    if (!user) {
      return res.status(404).json({ error: 'Użytkownik nie istnieje.' });
    }

    const isMatch = await bcrypt.compare(currentPassword, user.password_hash);
    if (!isMatch) {
      return res.status(400).json({ error: 'Obecne hasło jest niepoprawne.' });
    }

    const newHash = await bcrypt.hash(newPassword, 10);
    await db.run(`UPDATE users SET password_hash = ? WHERE id = ?`, [newHash, req.user.id]);
    res.json({ success: true, message: 'Hasło zostało pomyślnie zmienione.' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Błąd zmiany hasła serwera.' });
  }
});

router.post('/api/user/send-weekly-summary', summaryEmailLimiter, async (req, res) => {
  try {
    const customEmail = req.body.email;
    if (customEmail && !EMAIL_REGEX.test(customEmail)) {
      return res.status(400).json({ error: 'Niepoprawny format adresu e-mail.' });
    }
    await sendWeeklySummaryForUser(req.user.id, customEmail);
    res.json({
      success: true,
      message: 'Tygodniowe podsumowanie zostało pomyślnie wysłane.'
    });
  } catch (err) {
    console.error('[API ERROR] Failed to send the weekly summary:', err);
    res.status(500).json({ error: 'Błąd serwera podczas wysyłania e-maila: ' + err.message });
  }
});

// 6ii. Send the daily summary by email (Mailgun)
router.post('/api/user/send-daily-summary', summaryEmailLimiter, async (req, res) => {
  try {
    const customEmail = req.body.email;
    if (customEmail && !EMAIL_REGEX.test(customEmail)) {
      return res.status(400).json({ error: 'Niepoprawny format adresu e-mail.' });
    }
    await sendDailySummaryForUser(req.user.id, customEmail);
    res.json({
      success: true,
      message: 'Codzienne podsumowanie zostało pomyślnie wysłane.'
    });
  } catch (err) {
    console.error('[API ERROR] Failed to send the daily summary:', err);
    res.status(500).json({ error: 'Błąd serwera podczas wysyłania e-maila: ' + err.message });
  }
});

// 6iii. Send the monthly summary by email (Mailgun)
router.post('/api/user/send-monthly-summary', summaryEmailLimiter, async (req, res) => {
  try {
    const customEmail = req.body.email;
    if (customEmail && !EMAIL_REGEX.test(customEmail)) {
      return res.status(400).json({ error: 'Niepoprawny format adresu e-mail.' });
    }
    await sendMonthlySummaryForUser(req.user.id, customEmail);
    res.json({
      success: true,
      message: 'Miesięczne podsumowanie zostało pomyślnie wysłane.'
    });
  } catch (err) {
    console.error('[API ERROR] Failed to send the monthly summary:', err);
    res.status(500).json({ error: 'Błąd serwera podczas wysyłania e-maila: ' + err.message });
  }
});

// User data export (GDPR art. 20 - the right to data portability).
// The app processes health data (weight, body composition, activity, sleep) from
// Oura/Withings/Apple Health/Google Fit - a special category under GDPR art. 9 - so the
// user must be able to download their own data without asking an administrator.
// Passwords and secrets (password_hash, totp_secret, OAuth tokens) are deliberately
// EXCLUDED from the export: they are account security credentials, not 'personal data to
// be ported'.
router.get('/api/user/export', async (req, res) => {
  try {
    const userId = req.user.id;
    const user = await db.get(`
      SELECT username, email, first_name, last_name, role, created_at
      FROM users WHERE id = ?
    `, [userId]);
    if (!user) {
      return res.status(404).json({ error: 'Użytkownik nie istnieje.' });
    }

    const [settings, meals, healthMetrics, bodyMeasurements, workouts] = await Promise.all([
      db.all(`SELECT key, value FROM settings WHERE user_id = ?`, [userId]),
      // B-S1: skipping image_base64 prevents an OOM during a GDPR export on large accounts
      db.all(`SELECT id, user_id, date, timestamp, raw_text, calories, protein, carbs, fat, fiber, sugar, sodium, health_rating, analysis_json FROM meals WHERE user_id = ? ORDER BY timestamp`, [userId]),
      db.all(`SELECT * FROM health_metrics WHERE user_id = ? ORDER BY date`, [userId]),
      db.all(`SELECT * FROM body_measurements WHERE user_id = ? ORDER BY date`, [userId]),
      db.all(`SELECT * FROM apple_health_workouts WHERE user_id = ? ORDER BY date`, [userId])
    ]);

      // OAuth secrets and credentials (oura_client_secret, withings_client_secret,
      // and so on) are masked here as well: a data-portability export should not reveal
      // integration secrets in a file the user may save somewhere or forward on.
    const maskedSettings = {};
    settings.forEach(r => {
      maskedSettings[r.key] = maskSecretValue(r.key, r.value, USER_SECRET_SETTING_KEYS);
    });

    res.setHeader('Content-Disposition', 'attachment; filename="dietetyk-ai-eksport-danych.json"');
    res.json({
      exported_at: new Date().toISOString(),
      profile: {
        username: user.username,
        email: user.email,
        first_name: user.first_name,
        last_name: user.last_name,
        role: user.role,
        created_at: user.created_at
      },
      settings: maskedSettings,
      meals,
      health_metrics: healthMetrics,
      body_measurements: bodyMeasurements,
      apple_health_workouts: workouts
    });
  } catch (err) {
    console.error('[EXPORT ERROR]', err);
    res.status(500).json({ error: 'Błąd eksportu danych.' });
  }
});

// PDF export for a doctor or dietician (product feature) - independent of the JSON export
// above: this document is a concise, readable summary (targets, period averages, sleep and
// body composition, circumferences, supplements) rather than a raw dump of every database
// row. The days parameter is bounded in
// buildHealthReportPdf (services/pdfReport.js) do maks. PDF_REPORT_MAX_DAYS dni.
router.get('/api/user/export-pdf-report', async (req, res) => {
  try {
    const pdfBuffer = await buildHealthReportPdf(req.user.id, req.query.days);
    const dateStr = new Date().toISOString().slice(0, 10);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="dietetyk-ai-raport-${dateStr}.pdf"`);
    res.send(pdfBuffer);
  } catch (err) {
    console.error('[PDF EXPORT ERROR]', err);
    res.status(500).json({ error: 'Błąd generowania raportu PDF.' });
  }
});

// Sharing the PDF report by link (product feature: share a report by link, read-only) - an
// alternative to downloading the file above. Instead of sending the file to their doctor or
// dietician themselves, the user sends a link the recipient can open without an account in
// the app (see routes/sharedReport.js, the public
// endpoint zamontowany w server.js przed requireAuth).
router.post('/api/user/shared-reports', async (req, res) => {
  try {
    const validityKey = Object.prototype.hasOwnProperty.call(VALIDITY_OPTIONS_HOURS, req.body.validityKey)
      ? req.body.validityKey
      : undefined;
    const { token, days, expiresAt } = await createShareLink(req.user.id, req.body.days, validityKey);

    const appUrl = await getAppConfig('app_url');
    const base = appUrl ? appUrl.replace(/\/$/, '') : `${req.secure || req.headers['x-forwarded-proto'] === 'https' ? 'https' : 'http'}://${req.get('host')}`;
    const url = `${base}/api/public/shared-reports/${token}`;

    res.json({ url, days, expiresAt });
  } catch (err) {
    console.error('[SHARE LINK CREATE ERROR]', err);
    res.status(500).json({ error: 'Błąd tworzenia linku udostępniania.' });
  }
});

// The user's shares - without the tokens themselves (see the comment in listSharesForUser),
// only the metadata needed to display the history and allow revocation.
router.get('/api/user/shared-reports', async (req, res) => {
  try {
    const shares = await listSharesForUser(req.user.id);
    res.json({ shares });
  } catch (err) {
    console.error('[SHARE LIST ERROR]', err);
    res.status(500).json({ error: 'Błąd pobierania listy udostępnień.' });
  }
});

// Revoking a share - revokeShare checks ownership via user_id in the WHERE clause, so no
// additional check is needed here beyond the request being authenticated.
router.delete('/api/user/shared-reports/:id', async (req, res) => {
  try {
    const ok = await revokeShare(req.user.id, req.params.id);
    if (!ok) {
      return res.status(404).json({ error: 'Nie znaleziono udostępnienia.' });
    }
    res.json({ success: true });
  } catch (err) {
    console.error('[SHARE REVOKE ERROR]', err);
    res.status(500).json({ error: 'Błąd odwoływania udostępnienia.' });
  }
});

// Deleting one's own account (GDPR art. 17 - the right to erasure).
// Requires the current password, so that someone holding ONLY a session token - a browser
// left open, for instance - cannot permanently delete the account without knowing the
// password. Accounts signed in through Google with no password set (a theoretical case,
// since Google registration assigns a random hash) are covered by the same bcrypt check.
router.delete('/api/user/account', async (req, res) => {
  const { password } = req.body;
  if (!password) {
    return res.status(400).json({ error: 'Potwierdzenie hasłem jest wymagane do usunięcia konta.' });
  }

  try {
    const user = await db.get(`SELECT password_hash, role FROM users WHERE id = ?`, [req.user.id]);
    if (!user) {
      return res.status(404).json({ error: 'Użytkownik nie istnieje.' });
    }

    const isMatch = await bcrypt.compare(password, user.password_hash);
    if (!isMatch) {
      return res.status(400).json({ error: 'Niepoprawne hasło.' });
    }

    if (user.role === 'admin') {
      return res.status(403).json({
        error: 'Konto administratora nie może zostać usunięte samodzielnie z tego miejsca. Skontaktuj się z drugim administratorem lub usuń konto bezpośrednio w bazie danych.'
      });
    }

    // PRAGMA foreign_keys=ON (see db.js) ensures the rows linked to this user_id are
    // cascade-deleted (sessions, oauth_tokens, meals, settings,
    // health_metrics, body_measurements, apple_health_workouts).
    await db.run(`DELETE FROM users WHERE id = ?`, [req.user.id]);

    res.json({ success: true, message: 'Konto i wszystkie powiązane dane zostały usunięte.' });
  } catch (err) {
    console.error('[ACCOUNT DELETE ERROR]', err);
    res.status(500).json({ error: 'Błąd usuwania konta.' });
  }
});

module.exports = router;
